#!/usr/bin/env bash
# Pix3lTools Deploy - HTTPS setup via Traefik
# Generates docker-compose.override.yml and restarts the stack with HTTPS enabled
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo "========================================="
echo "  Pix3lTools Deploy - HTTPS Setup"
echo "========================================="
echo ""

# --- 1. Domain type ---
echo "[1/4] Configure domains"
echo ""
echo "  1) Custom domain  (e.g. board.example.com)"
echo "  2) sslip.io       (no domain needed, uses server IP)"
echo ""
read -rp "  Choice [1/2]: " DOMAIN_CHOICE
echo ""

case "$DOMAIN_CHOICE" in
  1)
    read -rp "  Pix3lBoard domain (e.g. board.example.com): " BOARD_DOMAIN
    read -rp "  Pix3lWiki domain  (e.g. wiki.example.com):  " WIKI_DOMAIN
    echo ""
    echo "  Important: DNS A records for both domains must point to this server's IP"
    echo "  before continuing. Let's Encrypt will fail if DNS is not propagated."
    echo ""
    read -rp "  DNS is configured. Continue? [y/N]: " DNS_OK
    if [[ ! "$DNS_OK" =~ ^[Yy]$ ]]; then
      echo "  Configure DNS first, then re-run this script."
      exit 0
    fi
    ;;
  2)
    echo "  Detecting public IP..."
    SERVER_IP=$(curl -sf --max-time 5 https://api.ipify.org 2>/dev/null || \
                curl -sf --max-time 5 https://ifconfig.me 2>/dev/null || \
                ip route get 1.1.1.1 2>/dev/null | grep -oP 'src \K\S+' || \
                hostname -I | awk '{print $1}')
    if [ -z "$SERVER_IP" ]; then
      echo "ERROR: Could not detect public IP. Use option 1 with a custom domain."
      exit 1
    fi
    BOARD_DOMAIN="board.${SERVER_IP}.sslip.io"
    WIKI_DOMAIN="wiki.${SERVER_IP}.sslip.io"
    echo "  Pix3lBoard: https://$BOARD_DOMAIN"
    echo "  Pix3lWiki:  https://$WIKI_DOMAIN"
    echo ""
    ;;
  *)
    echo "  Invalid choice. Run the script again and enter 1 or 2."
    exit 1
    ;;
esac

# --- 2. Email for Let's Encrypt ---
echo "[2/4] Let's Encrypt email"
read -rp "  Email: " ACME_EMAIL
if [ -z "$ACME_EMAIL" ]; then
  echo "ERROR: Email is required for Let's Encrypt."
  exit 1
fi
echo ""

# --- 3. Generate docker-compose.override.yml ---
echo "[3/4] Generating docker-compose.override.yml..."

cat > "$SCRIPT_DIR/docker-compose.override.yml" <<EOF
# Generated by setup-https.sh — re-run the script to update
services:
  traefik:
    image: traefik:v3
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=$ACME_EMAIL"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  pix3lboard:
    environment:
      NEXT_PUBLIC_APP_URL: "https://$BOARD_DOMAIN"
      PIX3LWIKI_URL: "https://$WIKI_DOMAIN"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.board.rule=Host(\`$BOARD_DOMAIN\`)"
      - "traefik.http.routers.board.entrypoints=websecure"
      - "traefik.http.routers.board.tls.certresolver=letsencrypt"
      - "traefik.http.services.board.loadbalancer.server.port=3000"

  pix3lwiki:
    environment:
      PIX3LBOARD_URL: "https://$BOARD_DOMAIN"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wiki.rule=Host(\`$WIKI_DOMAIN\`)"
      - "traefik.http.routers.wiki.entrypoints=websecure"
      - "traefik.http.routers.wiki.tls.certresolver=letsencrypt"
      - "traefik.http.services.wiki.loadbalancer.server.port=3001"

volumes:
  letsencrypt:
EOF

echo "  Created docker-compose.override.yml"

# --- 4. Firewall + restart ---
echo "[4/4] Applying configuration..."

if command -v ufw &> /dev/null; then
  ufw allow 80/tcp > /dev/null 2>&1 && echo "  Port 80 opened." || true
  ufw allow 443/tcp > /dev/null 2>&1 && echo "  Port 443 opened." || true
else
  echo "  ufw not found — make sure ports 80 and 443 are open in your firewall/cloud panel."
fi

cd "$SCRIPT_DIR"
docker compose up -d

# --- Smoke test: verify HTTP → HTTPS redirect ---
echo ""
echo "  Waiting for Traefik to start..."
sleep 5

HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 "http://$BOARD_DOMAIN" 2>/dev/null || echo "000")
if [[ "$HTTP_STATUS" == "301" || "$HTTP_STATUS" == "302" ]]; then
  echo "  HTTP→HTTPS redirect: OK (HTTP $HTTP_STATUS)"
else
  echo "  WARNING: HTTP redirect check returned $HTTP_STATUS (expected 301/302)."
  echo "  Traefik may still be starting. Verify manually:"
  echo "    curl -I http://$BOARD_DOMAIN"
fi

echo ""
echo "========================================="
echo "  HTTPS setup complete!"
echo "========================================="
echo ""
echo "  Pix3lBoard: https://$BOARD_DOMAIN"
echo "  Pix3lWiki:  https://$WIKI_DOMAIN"
echo ""
echo "  Certificates will be issued automatically on first access."
echo "  Watch Traefik logs: docker compose logs traefik -f"
echo ""
